### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scopeName' of undefined

### ISSUE THREAD

**Issue by paradox460** [atom/wrap-guide#26]
Open a new editor

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.2
**Thrown From**: [wrap-guide](https://github.com/atom/wrap-guide) package, v0.31.0

### Stack Trace

Uncaught TypeError: Cannot read property 'scopeName' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/wrap-guide/lib/wrap-guide-element.js:116

TypeError: Cannot read property 'scopeName' of undefined
  at wrap-guide.WrapGuideElement.updateGuide (/Applications/Atom.app/Contents/Resources/app/node_modules/wrap-guide/lib/wrap-guide-element.js:116:83)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/wrap-guide/lib/wrap-guide-element.js:28:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at atom-text-editor.TextEditorElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:95:27)
  at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:110:24)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:353:14)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:327:14)
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:534:16
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:564:44
  at flush (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:364:11)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "highlight-column",
      "save-session",
      "emacs-flow"
    ],
    "themes": [
      "quantum-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
atomatigit, v1.2.3
autocomplete-css, v0.3.0
autocomplete-emojis, v1.0.0
autocomplete-html, v0.2.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.3.0
autocomplete-snippets, v1.0.1
bezier-curve-editor, v0.6.5
color-picker, v1.4.4
crosshairs, v0.1.2
dash, v1.0.3
editor-stats, v0.17.0
file-icons, v1.5.0
git-log, v0.3.0
git-tab-status, v1.5.3
highlight-line, v0.10.1
highlight-selected, v0.9.1
html-entities, v0.3.1
language-fish-shell, v1.0.1
language-generic-config, v0.1.3
language-haml, v0.15.0
language-slim, v0.3.0
linter, v0.12.0
linter-coffeelint, v0.1.7
linter-js-yaml, v1.0.0
linter-jshint, v0.1.0
linter-rubocop, v0.2.2
mark-ring, v3.0.0
minimap, v4.4.0
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.0
minimap-selection, v4.2.0
pain-split, v1.3.1
preview-tabs, v0.1.6
project-manager, v1.15.5
quantum-ui, v0.2.0
quick-move-file, v0.7.0
red-wavy-underline, v0.2.4
regex-railroad-diagram, v0.7.1
ruby-block, v0.2.2
set-syntax, v0.2.1
tree-view-open-files, v0.2.3
underline-trailing-whitespace, v1.0.1
view-tail-large-files, v0.1.13
vim-mode, v0.34.0
vim-surround, v0.4.2
white-cursor, v0.5.2

# Dev
No dev packages
```

**Comment by paradox460** [comment]
Was due to a bug in an init.coffee script, not the package
