### ISSUE TITLE
Failed to load the wrap-guide package

### ISSUE THREAD

**Issue by theniceboy** [atom/wrap-guide#34]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [wrap-guide](https://github.com/atom/wrap-guide) package, v0.35.0

### Stack Trace

Failed to load the wrap-guide package

```
At Failed to execute 'registerElement' on 'Document': Registration failed for type 'wrap-guide'. A type with that name is already registered.

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'wrap-guide'. A type with that name is already registered.
  at Error (native)
  at Object.<anonymous> (/Users/David/.atom/packages/wrap-guide/lib/wrap-guide-element.coffee:93:10)
  at Object.<anonymous> (/Users/David/.atom/packages/wrap-guide/lib/wrap-guide-element.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/David/.atom/packages/wrap-guide/lib/main.coffee:3:20)
  at Object.<anonymous> (/Users/David/.atom/packages/wrap-guide/lib/main.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:188:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:179:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:372:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:451:30)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -1:05.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:41.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  5x -0:40 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai-syntax-for-one-dark"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.7.0
autocomplete-php, v0.3.6
color-picker, v2.0.7
css-snippets, v0.8.0
file-icons, v1.5.8
linter, v1.0.9
linter-chktex, v0.3.0
linter-csslint, v0.0.14
linter-php, v0.0.15
minimap, v4.10.0
monokai-syntax-for-one-dark, v0.2.2
php-debug, v0.1.2
pigments, v0.8.0
tree-view-git-status, v0.1.1
wrap-guide, v0.35.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
Why do you have wrap-guide manually installed? Since it's a core package it already ships with Atom - you should remove the manually installed version of wrap guide (it should be in `~/.atom/packages`).
