### ISSUE TITLE
Failed to activate the wrap-guide package

### ISSUE THREAD

**Issue by regisnew** [atom/wrap-guide#35]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 14.04.2
**Thrown From**: [wrap-guide](https://github.com/atom/wrap-guide) package, v0.35.0
### Stack Trace

Failed to activate the wrap-guide package

```
At Cannot read property 'scopeName' of undefined

TypeError: Cannot read property 'scopeName' of undefined
    at wrap-guide.WrapGuideElement.updateGuide (/usr/share/atom/resources/app.asar/node_modules/wrap-guide/lib/wrap-guide-element.js:129:83)
    at wrap-guide.WrapGuideElement.initialize (/usr/share/atom/resources/app.asar/node_modules/wrap-guide/lib/wrap-guide-element.js:21:12)
    at /usr/share/atom/resources/app.asar/node_modules/wrap-guide/lib/main.js:14:58
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:276:9)
    at Object.module.exports.activate (/usr/share/atom/resources/app.asar/node_modules/wrap-guide/lib/main.js:11:29)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:240:19)
    at /usr/share/atom/resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:452:21)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "material"
    ],
    "fileEncoding": "iso88591"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-php, v0.3.6
linter-php, v0.0.15
linter-phpcs, v0.0.15
linter-phpmd, v0.0.11
material, v2.1.4
php-getters-setters, v0.5.5

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
No further reports.
