### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidChangeScrollLeft' of null

### ISSUE THREAD

**Issue by wec22** [atom/wrap-guide#43]
[Enter steps to reproduce below:]

1. split screen horizontally
2. drag file from left side to right side

**Atom Version**: 1.2.0-dev-3ad9bb3
**System**: Ubuntu 15.04 32-bit
**Thrown From**: [wrap-guide](https://github.com/atom/wrap-guide) package, v0.36.0

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeScrollLeft' of null

```
At /usr/share/atom/resources/app.asar/src/text-editor-element.js:281

TypeError: Cannot read property 'onDidChangeScrollLeft' of null
  at atom-text-editor.TextEditorElement.onDidChangeScrollLeft (/usr/share/atom/resources/app.asar/src/text-editor-element.js:281:28)
  at TextEditor.module.exports.TextEditor.onDidChangeScrollLeft (/usr/share/atom/resources/app.asar/src/text-editor.js:351:39)
  at wrap-guide.WrapGuideElement.handleEvents (/usr/share/atom/resources/app.asar/node_modules/wrap-guide/lib/wrap-guide-element.js:45:39)
  at wrap-guide.WrapGuideElement.initialize (/usr/share/atom/resources/app.asar/node_modules/wrap-guide/lib/wrap-guide-element.js:20:12)
  at /usr/share/atom/resources/app.asar/node_modules/wrap-guide/lib/main.js:14:58
  at /usr/share/atom/resources/app.asar/src/workspace.js:272:16
  at /usr/share/atom/resources/app.asar/src/workspace.js:333:18
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/share/atom/resources/app.asar/src/pane-container.js:349:27)
  at /usr/share/atom/resources/app.asar/src/pane-container.js:336:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app.asar/src/pane.js:336:20)
  at Pane.module.exports.Pane.moveItemToPane (/usr/share/atom/resources/app.asar/src/pane.js:421:19)
  at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:706:20)
  at TabBarView.module.exports.TabBarView.onDrop (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:632:23)
  at space-pen-ul.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -0:28.9.0 window:toggle-dev-tools (atom-text-editor.editor.mini)
     -0:13.4.0 application:open-file (div.settings-view.pane-item)
     -0:05.8.0 pane:split-right (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-glsl, v0.2.3
hyperclick, v0.0.32
language-glsl, v2.0.1
language-lua, v0.9.4
linter, v1.5.0
love-ide, v0.4.0
tool-bar, v0.1.8
tool-bar-almighty, v0.0.3

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
I just ran into this too; identical repro steps. /cc @as-cii Maybe the wrap-guide is trying to call `::onDidChangeScrollLeft` on a text-editor whose element isn't on the DOM yet?
